module "cloudfront_distribution" {
  source                         = "../../"
  acm_certificate_arn            = var.acm_certificate_arn
  aliases                        = var.aliases
  cloudfront_default_certificate = var.cloudfront_default_certificate
  comment                        = var.comment
  common_tags                    = var.common_tags
  default_cache                  = var.default_cache
  default_root_object            = var.default_root_object
  distribution_enabled           = var.distribution_enabled
  domain_name                    = var.domain_name
  ipv6_enabled                   = var.ipv6_enabled
  logging_config                 = var.logging_config
  logging_include_cookies        = var.logging_include_cookies
  origin                         = var.origin
  price_class                    = var.price_class
  restriction_locations          = var.restriction_locations
  restriction_type               = var.restriction_type
  ssl_support_method             = var.ssl_support_method
  web_acl_id                     = var.web_acl_id
}
